config/routes.rb
Rails.application.routes.draw do
  resources :auths
  resources :roles do
    resource :auths
  end
  resources :users
  get 'admin/index'
  get 'tmc/index'
  root 'tmc#index'
  resources :comments

end

app/models/auth.rb
class Auth < ActiveRecord::Base

  before_destroy{ DeleteSonAuth(:id) }



  private
  def DeleteSonAuth(column)
    #删除权限之前 删除子权限
    Auth.where("auth_pid=#{self[column]}").each do |a|
      a.destroy
    end
  end
end

app/controllers/auths_controller.rb
class AuthsController < ApplicationController
  before_action :set_auth, only: [:show, :edit, :update, :destroy]
  caches_page :show, :new
  # GET /auths
  # GET /auths.json
  def index
    @auths = Auth.all.order(:auth_path)
  end

  # GET /auths/1
  # GET /auths/1.json
  def show
  end

  # GET /auths/new
  def new
    @auth = Auth.new
  end

  # GET /auths/1/edit
  def edit
  end

  # POST /auths
  # POST /auths.json
  def create
    @auth = Auth.new(auth_params)
    respond_to do |format|
      if @auth.save
        #权限保存成功后的操作
        #添加权限的全路径 和 权限级别
        #如果权限是顶级菜单 那么 auth_path = 自己的id
        #@auth.auth_path = @auth.id
        if @auth.auth_pid == 0
          @auth.auth_path = @auth.id
          @auth.auth_level =  0
        else
          #如果权限不是顶级菜单 那么auth_path = 上级的全路径-自己的id
          parent =Auth.find_by_id(@auth.auth_pid)
          @auth.auth_path ="#{parent.auth_path}-#{@auth.id}"
          @auth.auth_level = parent.auth_level + 1
        end
        @auth.save
        format.html { redirect_to @auth, notice: 'Auth was successfully created.' }
        format.json { render :show, status: :created, location: @auth }
      else
        format.html { render :new }
        format.json { render json: @auth.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /auths/1
  # PATCH/PUT /auths/1.json
  def update
    respond_to do |format|
      if @auth.update(auth_params)
        if @auth.auth_pid == 0
           @auth.auth_path = @auth.id
           @auth.auth_level =  0
        else
          #如果权限不是顶级菜单 那么auth_path = 上级的全路径-自己的id
           parent =Auth.find_by_id(@auth.auth_pid)
           @auth.auth_path ="#{parent.auth_path}-#{@auth.id}"
           @auth.auth_level = parent.auth_level + 1
        end
        @auth.save
        ChangeAuthSon(@auth)
        format.html { redirect_to @auth, notice: 'Auth was successfully updated.' }
        format.json { render :show, status: :ok, location: @auth }
      else
        format.html { render :edit }
        format.json { render json: @auth.errors, status: :unprocessable_entity }
      end
    end
  end


  #更新子权限
  def ChangeAuthSon(auth)
    #判断是否拥有子权限
    sonauth = Auth.where("auth_pid==?",auth.id).all
    if sonauth
      #子权限也根据父权限来进行相应的修改
      sonauth.each do |s|
        s.auth_path = "#{auth.auth_path}-#{s.id}"
        s.auth_level = auth.auth_level + 1
        s.save
        ChangeAuthSon(s)
      end
    end


  end

  # DELETE /auths/1
  # DELETE /auths/1.json
  def destroy

    # sonauth.each do |s|
    #   s.destroy
    # end
    #DeleteSonAuth(@auth)
     @auth.destroy
    respond_to do |format|
      format.html { redirect_to auths_url, notice: 'Auth was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_auth
      @auth = Auth.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def auth_params
      params.require(:auth).permit(:auth_name, :auth_pid, :auth_controller, :auth_action)
    end
end

app/helpers/auths_helper.rb
module AuthsHelper
end

app/views/auths/_authlist.html.erb
<% if Auth.where("auth_pid==?",auth.id).all  %>
    <% if auth.auth_level == 0 %>
        <%= auth.auth_name%>
    <% end %>


    <%Auth.where("auth_pid==?",auth.id).all.each do |a|  %>
        <%= render partial: "roles/authlist",locals: {auth:a} %>
    <% end %>
<% else %>
    <input type="checkbox" /><%= auth.auth_name%>
<% end %>

app/views/auths/_form.html.erb
<%= form_for(@auth) do |f| %>
  <% if @auth.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@auth.errors.count, "error") %> prohibited this auth from being saved:</h2>

      <ul>
      <% @auth.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :auth_name %><br>
    <%= f.text_field :auth_name %>
  </div>
  <div class="field">
    <%= f.label :auth_pid %><br>
    <%= f.select :auth_pid,options_for_select(Auth.where("id!=?",@auth.id ? @auth.id : 0).all.unshift(Auth.new(:auth_name=>"请选择",:id=>0)).map{ |c| [c.auth_name, c.id] },:selected=>@auth.auth_pid) %>
  </div>
      <%#= Auth.where("id!=#{@auth.id}").to_sql%>
    <%#= f.select(:city_id) do %>
        <%# [['Lisbon', 1], ['Madrid', 2]].each do |c| -%>
            <%#= content_tag(:option, c.first, value: c.last) %>
        <%# end %>
    <%# end %>

  <div class="field">
    <%= f.label :auth_path %><br>
    <%= f.text_field :auth_path %>
  </div>
  <div class="field">
    <%= f.label :auth_controller %><br>
    <%= f.text_field :auth_controller %>
  </div>
  <div class="field">
    <%= f.label :auth_action %><br>
    <%= f.text_field :auth_action %>
  </div>
  <div class="field">
    <%= f.label :auth_level %><br>
    <%= f.number_field :auth_level %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/auths/edit.html.erb
<h1>Editing Auth</h1>

<%= render 'form' %>

<%= link_to 'Show', @auth %> |
<%= link_to 'Back', auths_path %>

app/views/auths/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Auths</h1>

<table>
  <thead>
    <tr>
      <th>Auth name</th>
      <th>Auth pid</th>
      <th>Auth path</th>
      <th>Auth controller</th>
      <th>Auth action</th>
      <th>Auth level</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @auths.each do |auth| %>
      <tr>
        <td><%= auth.auth_name %></td>
        <td><%= auth.auth_pid %></td>
        <td><%= auth.auth_path %></td>
        <td><%= auth.auth_controller %></td>
        <td><%= auth.auth_action %></td>
        <td><%= auth.auth_level %></td>
        <td><%= link_to 'Show', auth %></td>
        <td><%= link_to 'Edit', edit_auth_path(auth) %></td>
        <td><%= link_to 'Destroy', auth, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Auth', new_auth_path %>

app/views/auths/new.html.erb
<h1>New Auth</h1>

<%= render 'form' %>

<%= link_to 'Back', auths_path %>

app/views/auths/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Auth name:</strong>
  <%= @auth.auth_name %>
</p>

<p>
  <strong>Auth pid:</strong>
  <%= @auth.auth_pid %>
</p>

<p>
  <strong>Auth path:</strong>
  <%= @auth.auth_path %>
</p>

<p>
  <strong>Auth controller:</strong>
  <%= @auth.auth_controller %>
</p>

<p>
  <strong>Auth action:</strong>
  <%= @auth.auth_action %>
</p>

<p>
  <strong>Auth level:</strong>
  <%= @auth.auth_level %>
</p>

<%= link_to 'Edit', edit_auth_path(@auth) %> |
<%= link_to 'Back', auths_path %>